server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chat?serverTimezone=GMT%2B8
    username: root
    password: 11111111

#开启日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:


file:
  upload-path: D:\idea document\InstantMessageUserInterfaceService\src\main\resources\static\


